sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 15193651772Aa!
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFsgXkTZ1LqBx4H5NLR
    access-key-secret: ZhmmmFZkQJOFm8YH3cMZNODLdNYont
    bucket-name: leadnews1772
  wechat:
    appid: wx6e1a75c9a8dc180a
    secret: 2b7d75d8316b016d1381771b3480c3da
  redis:
    host: localhost
    port: 6379
    # password: (当前无密码)
    database: 0