sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 15193651772Aa!
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: leadnews1772
  redis:
    host: localhost
    port: 6379
    # password: (当前无密码)
    database: 0